### ISSUE TITLE
Vaccination note details view (EN) links to German https://reopen.europa.eu/de

### ISSUE THREAD

**Issue by MikeMcC399** [Digitaler-Impfnachweis/covpass-apps-i18n#10]
## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- CovPass-App version: 1.28.3

## Describe the bug

The English text "This certificate is not a travel document ..." links to the German-language page https://reopen.europa.eu/de instead of the English-language page https://reopen.europa.eu/en.

## Steps to reproduce the issue

1. Set locale to Deutsch (Deutschland)
2. Open CovPass-App
3. Tap on "+" to add a digital certificate
4. Tap on "QR-Code scannen" and scan in a valid EU digital COVID vaccination certificate
5. Scroll down to "EU-Zertifikate"
6. Tap on right arrow
7. Scroll down to screen starting "Diese Bescheinigung ist kein Reisedokument ..."

![reopen](https://user-images.githubusercontent.com/66998419/125332387-471af980-e349-11eb-8e88-25d1dcf4f3ab.jpg)

## Expected behavior

The English-language text should link to the English-language page https://reopen.europa.eu/en

## Possible Fix

Change the English-language text to link to the English-language page https://reopen.europa.eu/en

## Additional context

Please publish translated texts to this repository, or describe in the [README.md](https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/blob/main/README.md) how you would like to receive feedback and/or suggestions for change regarding German or translated texts. 

I can only find the German language text here, not the translation into English:

https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/blob/3d797a46037a2eb7cc3fe9ded19beaae9da5629d/twine-cert.txt#L580-L581

**Comment by timokoenig** [comment]
reopen.europa.eu will automatically select the language based on users device preferences. I created a pull request that will take care of it

https://github.com/Digitaler-Impfnachweis/covpass-apps-i18n/pull/11

**Comment by MikeMcC399** [comment]
@timokoenig 
That works with Google Chrome on Android.
