### ISSUE TITLE
Rechtschreibfehler "Zertifkate" in app_information_offline_revocation_copy_1

### ISSUE THREAD

**Issue by vgx** [Digitaler-Impfnachweis/covpass-apps-i18n#332]
Rechtschreibfehler "Zertifkate" im Text

`[app_information_offline_revocation_copy_1]`
`    de = Hier können Sie die Regeln aktualisieren, nach denen Zertifkate geprüft werden. Sollte Ihr Smartphone üblicherweise mit dem Internet verbunden sein, passiert das automatisch.`

Laut github.com/search drei Vorkommen in

Digitaler-Impfnachweis/covpass-ios
Source/CovPassCheckApp/Source/Resources/Locale/de.lproj/Localizable.strings

Digitaler-Impfnachweis/covpass-android
common-app-covpass-check/src/main/res/values-de/generated_strings.xml

Digitaler-Impfnachweis/covpass-apps-i18n
/twine-validator.txt

**Comment by pucherd** [comment]
Hello @vgx, Thank you for reporting it. Will be fixed in our next version 1.40.
